// ==UserScript==
// @name         专业捕鸟人
// @namespace    http://tampermonkey.net/5GVBKlRpx98iVhG/mu2XMB
// @version      20241210
// @author       Bob
// @description  合作加vx
// @icon         https://github.com/faner11/faner11-bird-hunter/blob/main/IMG_5007.jpeg?raw=true
// @downloadURL  https://github.com/faner11/faner11-bird-hunter/raw/main/bird-hunter.user.js
// @updateURL    https://github.com/faner11/faner11-bird-hunter/raw/main/bird-hunter.meta.js
// @match        https://arcteryx.com/*
// @match        https://outlet.arcteryx.com/*
// @match        http://localhost:*/*
// @match        https://*.goodhunter.cc/*
// @resource     vconsole  https://cdn.jsdelivr.net/npm/vconsole@latest/dist/vconsole.min.js
// @connect      mixpanel.com
// @grant        GM.addElement
// @grant        GM.addStyle
// @grant        GM.deleteValue
// @grant        GM.getResourceUrl
// @grant        GM.getValue
// @grant        GM.info
// @grant        GM.listValues
// @grant        GM.notification
// @grant        GM.openInTab
// @grant        GM.registerMenuCommand
// @grant        GM.setClipboard
// @grant        GM.setValue
// @grant        GM.xmlHttpRequest
// @grant        GM_addElement
// @grant        GM_addStyle
// @grant        GM_addValueChangeListener
// @grant        GM_cookie
// @grant        GM_deleteValue
// @grant        GM_download
// @grant        GM_getResourceText
// @grant        GM_getResourceURL
// @grant        GM_getTab
// @grant        GM_getTabs
// @grant        GM_getValue
// @grant        GM_info
// @grant        GM_listValues
// @grant        GM_log
// @grant        GM_notification
// @grant        GM_openInTab
// @grant        GM_registerMenuCommand
// @grant        GM_removeValueChangeListener
// @grant        GM_saveTab
// @grant        GM_setClipboard
// @grant        GM_setValue
// @grant        GM_unregisterMenuCommand
// @grant        GM_webRequest
// @grant        GM_xmlhttpRequest
// @grant        unsafeWindow
// @grant        window.close
// @grant        window.focus
// @grant        window.onurlchange
// @run-at       document-start
// ==/UserScript==